audit:
  masked-fields:
    - password
    - mobNo
    - dateOfBirth
  retention:
    days: 1825

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: FogPassEOELProject

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false