package train.local.fogpass.entity.logs; // Placed in the correct sub-package

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A minimal MachineLog entity that creates a database table
 * named 'machine_log' with only a primary key column.
 */
@Entity
@Table(name = "machine_log") // Explicitly naming the table
public class MachineLog {

    @Id // Marks this field as the primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database.
    private Long id;

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}