package train.local.fogpass.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A minimal Device entity that creates a database table
 * named 'device' with only a primary key column.
 */
@Entity
@Table(name = "device") // Specifies the table name as 'device'
public class Device {

    @Id // Marks this field as the primary key (mandatory for an entity).
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database.
    private Long id;

    // --- Getters and Setters (optional but good practice) ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}