package train.local.fogpass.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A minimal Division entity that creates a database table
 * named 'division' with only a primary key column.
 */
@Entity
@Table(name = "division") // Specifies the table name as 'division'
public class Division {

    @Id // Marks this field as the primary key. This is required.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database.
    private Long id;

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}